const AngelinaIrvine = {
    "_id": "6344e797065fcdb559a84d41",
    "yelpRestaurantId": "uZqBQCiyZC3owwct3CUJkA",
    "name": "Angelina's Pizzeria Napoletana",
    "telNumber": "+19495365200",
    "displayNumber": "(949) 536-5200",
    "address1": "8573 Irvine Center Dr",
    "address2": null,
    "address3": "",
    "city": "Irvine",
    "zip_code": "92618",
    "country": "US",
    "state": "CA",
    "latitude": 33.6458630625593,
    "longitude": -117.74306674205,
    "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/2vmY6wfVW3LRap0DFS-Ayw/o.jpg",
    "hasDrinks": true,
    "hasFood": true,
    "dogFriendly": false,
    "hasPatio": false,
    "cuisines": [
        "Pizza",
        "Italian",
        "Cocktail Bars"
    ],
    "regulars": [],
    "hours": [
        {
            "day": 0,
            "hasHH1": true,
            "start1": 16.5,
            "end1": 18.5,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 1,
            "hasHH1": true,
            "start1": 16.5,
            "end1": 18.5,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 2,
            "hasHH1": true,
            "start1": 16.5,
            "end1": 18.5,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 3,
            "hasHH1": true,
            "start1": 16.5,
            "end1": 18.5,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 4,
            "hasHH1": false,
            "start1": -1,
            "end1": -1,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 5,
            "hasHH1": false,
            "start1": -1,
            "end1": -1,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        },
        {
            "day": 6,
            "hasHH1": true,
            "start1": 16.5,
            "end1": 18,
            "end1close": false,
            "hasHH2": true,
            "start2": 21,
            "end2": -1,
            "end2close": true,
        }
    ],
    "menu": {
        "restaurantName": "Angelina's Pizzeria Napoletana",
        "isChain": false,
        "hasFoodSpecials": true,
        "foodSpecialsDescription": "",
        "hasDrinkSpecials": true,
        "drinkSpecialsDescription":"",
        "restaurant": [],
        "foodMenu": [
            {
                "name": "POLPETTE AL SUGO",
                "description": "Napoletana-style meatballs",
                "value": 13,
                "specialTypeId": 1,
            },
            {
                "name": "BRUSCHETTA CLASSICA",
                "description": "",
                "value": 7,
                "specialTypeId": 1,
            },
            {
                "name": "PROSCIUTTO & PARMIGIANO",
                "description": "sliced prosciutto, Parmigiano-Reggiano cheese, giardiera",
                "value": 11,
                "specialTypeId": 1,
            },
            {
                "name": "PIZZETTA DIAVOLA BIANCA",
                "description": "flatbread topped with mozzarella di bufala, Napoletana-style spicy salame",
                "value": 9,
                "specialTypeId": 1,
            },
            {
                "name": "PIZZETTA ALLE MELANZANE",
                "description": "Flat bread topped with eggplant, gorgonzola cheese, mozzarella di bufala, DOP pomodoro sauce, basil, EVOO",
                "value": 9,
                "specialTypeId": 1,
                
            },
            {
                "name": "BRESAOLA & UBRIACO",
                "description": "Sliced bresaola, Ubriaco di Piave cheese, giardiera",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "BURRATA & POMODORI",
                "description": "burrata, heirloom tomatoes, Taggiasca olives, basil",
                "value": 11,
                "specialTypeId": 1,
            }
        ],
        "drinkMenu": [
            {
                "name": "WINE",
                "description": "Red, White, Prosecco",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "BEER",
                "description": "All Beers",
                "value": 6,
                "specialTypeId": 1,
            },
            {
                "name": "APEROL SPRTIZ",
                "description": "Aperol, Prosecco, soda water",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "IL DOTTORE",
                "description": "Vodka, lemongrass syrup, simple syrup, ginger",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "OLD FASHIONED",
                "description": "Bourbon, bitters, demerara",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "SIDECAR",
                "description": "Copper and Kings Brandy, triple sec, lemon",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "MANHATTAN",
                "description": "Rye Whiskey, vermouth, bitters",
                "value": 10,
                "specialTypeId": 1,
            },
            {
                "name": "WELL LIBATIONS",
                "description": "Vodka, Gin, Rum, Tequila, Bourbon, Rye Whiskey",
                "value": 10,
                "specialTypeId": 1,
            }
        ]
    }
}

const YardHouseIrvine = {
    "_id": "6345fda3084c67c6e16996d8",
    "yelpRestaurantId": "dNvvKds1D5MQM8bNfSuUfA",
    "name": "Yard House",
    "telNumber": "+19497539373",
    "displayNumber": "(949) 753-9373",
    "address1": "620 Spectrum Center Dr",
    "address2": "",
    "address3": "",
    "city": "Irvine",
    "zip_code": "92618",
    "country": "US",
    "state": "CA",
    "latitude": 33.650329,
    "longitude": -117.745125,
    "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/zs1dLeED0DveEvIrs6NfnA/o.jpg",
    "hasDrinks": true,
    "hasFood": true,
    "dogFriendly": true,
    "hasPatio": true,
    "cuisines": [
        "American (New)",
        "Bars",
        "Vegetarian"
    ],
    "regulars": [],
    "hours": [
        {
            "day": 0,
            "hasHH1": true,
            "start1": 15,
            "end1": 18,
            "end1close": false,
            "hasHH2": true,
            "start2": 22,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996da",
            "createdAt": "2022-10-11T23:34:59.467Z",
            "updatedAt": "2022-10-11T23:34:59.467Z"
        },
        {
            "day": 1,
            "hasHH1": true,
            "start1": 15,
            "end1": 18,
            "end1close": false,
            "hasHH2": true,
            "start2": 22,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996db",
            "createdAt": "2022-10-11T23:34:59.469Z",
            "updatedAt": "2022-10-11T23:34:59.469Z"
        },
        {
            "day": 2,
            "hasHH1": true,
            "start1": 15,
            "end1": 18,
            "end1close": false,
            "hasHH2": true,
            "start2": 22,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996dc",
            "createdAt": "2022-10-11T23:34:59.469Z",
            "updatedAt": "2022-10-11T23:34:59.469Z"
        },
        {
            "day": 3,
            "hasHH1": true,
            "start1": 15,
            "end1": 18,
            "end1close": false,
            "hasHH2": false,
            "start2": -1,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996dd",
            "createdAt": "2022-10-11T23:34:59.469Z",
            "updatedAt": "2022-10-11T23:34:59.469Z"
        },
        {
            "day": 4,
            "hasHH1": true,
            "start1": 15,
            "end1": 18,
            "end1close": false,
            "hasHH2": false,
            "start2": -1,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996de",
            "createdAt": "2022-10-11T23:34:59.469Z",
            "updatedAt": "2022-10-11T23:34:59.469Z"
        },
        {
            "day": 5,
            "hasHH1": false,
            "start1": -1,
            "end1": -1,
            "end1close": false,
            "hasHH2": false,
            "start2": -1,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996df",
            "createdAt": "2022-10-11T23:34:59.469Z",
            "updatedAt": "2022-10-11T23:34:59.469Z"
        },
        {
            "day": 6,
            "hasHH1": false,
            "start1": -1,
            "end1": -1,
            "end1close": false,
            "hasHH2": true,
            "start2": 22,
            "end2": -1,
            "end2close": true,
            "_id": "6345fda3084c67c6e16996e0",
            "createdAt": "2022-10-11T23:34:59.470Z",
            "updatedAt": "2022-10-11T23:34:59.470Z"
        }
    ],
    "createdAt": "2022-10-11T23:34:59.409Z",
    "updatedAt": "2022-10-11T23:34:59.479Z",
    "__v": 1,
    "menu": {
        "_id": "6345fda3084c67c6e16996e1",
        "restaurantName": "Yard House",
        "isChain": true,
        "hasFoodSpecials": true,
        "hasDrinkSpecials": true,
        "restaurant": [
            "6345fda3084c67c6e16996d8"
        ],
        "foodMenu": [
            {
                "name": "FOUR CHEESE SPINACH DIP",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996eb",
                "createdAt": "2022-10-11T23:34:59.494Z",
                "updatedAt": "2022-10-11T23:34:59.494Z"
            },
            {
                "name": "MIGUEL'S QUESO DIP",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996ec",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "POKE NACHOS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996ed",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "CHICKEN NACHOS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996ee",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "CHICKEN LETTUCE WRAPS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996ef",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "HAND-BATTERED CHICKEN TENDERS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f0",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "CLASSIC SLIDERS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f1",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "WISCONSIN FRIED CHEESE CURDS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f2",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "BLACKENED AHI SASHIMI",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f3",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "FRIED CALAMARI",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f4",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "BONELESS WINGS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f5",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "GARDEIN WINGS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f6",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "CARNIVORE PIZZA",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f7",
                "createdAt": "2022-10-11T23:34:59.496Z",
                "updatedAt": "2022-10-11T23:34:59.496Z"
            },
            {
                "name": "PEPPERONI & MUSHROOM PIZZA",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f8",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            },
            {
                "name": "THREE CHEESE PIZZA",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996f9",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            },
            {
                "name": "MARGHERITA PIZZA",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996fa",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            },
            {
                "name": "BBQ CHICKEN PIZZA",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": true,
                "isDollarsOff": false,
                "dollarsOff": 0,
                "_id": "6345fda3084c67c6e16996fb",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            }
        ],
        "drinkMenu": [
            {
                "name": "DRAFT BEER, WINE, SPIRITS & COCKTAILS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": false,
                "isDollarsOff": true,
                "dollarsOff": 2,
                "_id": "6345fda3084c67c6e16996fc",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            },
            {
                "name": "9oz WINE",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": false,
                "isDollarsOff": true,
                "dollarsOff": 3,
                "_id": "6345fda3084c67c6e16996fd",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            },
            {
                "name": "HALF YARDS",
                "description": "",
                "isPrice": false,
                "price": 0,
                "isPercentDiscount": false,
                "isDollarsOff": true,
                "dollarsOff": 4,
                "_id": "6345fda3084c67c6e16996fe",
                "createdAt": "2022-10-11T23:34:59.497Z",
                "updatedAt": "2022-10-11T23:34:59.497Z"
            }
        ],
        "createdAt": "2022-10-11T23:34:59.441Z",
        "updatedAt": "2022-10-11T23:34:59.498Z",
        "__v": 1
    }
}
